urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()
admin.site.login_template = 'webauth/admin_redirect.html'

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.MEDIA_ROOT}),
    (r'^admin/', include(admin.site.urls)),
    (r'^webauth/', include('webauth.urls')),
    (r'^api/', include('waivers_api.urls')),
    (r'^', include('assu_waivers.urls')),

)

assu_waivers/models.py
from django.db import models

POPULATIONS = ((0, "Undergraduate"), (1, "Graduate"), )


class Term(models.Model):
    short_name = models.SlugField(max_length=5,blank=False, verbose_name="Term", help_text="SSC short code for the quarter - see <a href ='/reports/term_info'>this document</a>")
    long_name = models.CharField(max_length=128, blank=False, verbose_name="Term name", help_text="e.g. Winter 2010-2011")
    refund_opens = models.DateTimeField(blank=False, verbose_name="Date/time this waiver period opens", help_text="8:00 AM on the first day of the quarter. The system will automatically open at this date/time.")
    refund_closes = models.DateTimeField(blank=False, verbose_name="Date/time this waiver period closes", help_text="5:00 PM on the second Friday of the quarter. The system will automatically close at this date/time.")

    def __unicode__(self):
        return self.long_name


class Student(models.Model):
    suid = models.CharField(max_length=8, primary_key=True, verbose_name="SUID #", help_text="e.g. 05555555")
    sunetid = models.CharField(max_length=8, verbose_name='SUNetID',help_text="e.g. joeblow")
    name = models.CharField(max_length=128, verbose_name='Full Name',help_text="e.g. Blow,Joe Q")
    no_waiver = models.BooleanField(default=False, verbose_name="No Waivers Allowed", help_text="This student may not receive any waivers (e.g., because he/she is an NCAA athlete)")
    terms = models.ManyToManyField(Term,through="Enrollment")

    def __unicode__(self):
        return self.sunetid

    @staticmethod
    def popFromRegistrarStatus(status):
        if status == "UG":
            return 0
        elif status == "GR" or status == "LAW" or status == "GSB" or status == "MED":
            return 1
        else:
            raise Exception("Unexpected registration status provided: %s" % status)


class Enrollment(models.Model):
    student = models.ForeignKey(Student)
    term = models.ForeignKey(Term)
    population = models.IntegerField(choices=POPULATIONS)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('student', 'term')

    def __unicode__(self):
        return "%s (%s)" % (self.student.sunetid, self.term.short_name)


class Fee(models.Model):
    name = models.CharField(max_length=128, verbose_name="Fee name",help_text="Group name or general fee name")
    population = models.IntegerField(choices=POPULATIONS, help_text="May only be applied to one population. Create multiple identically named fees if necessary.")
    term = models.ForeignKey(Term)
    max_amount = models.FloatField(blank=False)

    def __unicode__(self):
        return "%s (%s)" % (self.name,self.term)


class FeeWaiver(models.Model):
    student = models.ForeignKey(Student)
    fee = models.ForeignKey(Fee)
    amount = models.FloatField()
    reason = models.TextField()
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('student','fee')

templates/waivers/admin/docs_use.html
{% extends 'waivers/admin/report_base.html' %}

{% block title %}
    Term name information
{% endblock %}
{% block reportname %}
    Term name information
{% endblock %}

{% block content %}
<h2>Fee Waiver Portal Administrator Documentation</h2>
<p>Welcome, refunds coordinator and ASSU Financial Manager! This fee waiver portal is a tool that will hopefully
    be useful to you in managing the required fee waiver process. This portal was developed to help the
process that was developed in the 2010-11 school year for waivers, which we'll describe below.</p>

<h3>A brief overview of the waivers process</h3>
    <ol>
    <li>Well before the quarter starts, the Student Services Center (SSC) works with the ASSU Financial Manager
    to be sure that we have a strong working relationship and that any changes to the process are documented
    and understood by all parties. For instance, for fall quarter, this needs to happen in early August.</li>
    <li>Create the quarter in the waivers system</li>
    <li>Add the fees that were for the quarter into the waivers system. Take this data from the ASSU Fee Budget
    and make sure the numbers used in the waivers system are the amounts actually collected for the group.</li>
    <li>Receive the list of students and the list of athletes from the SSC</li>
    <li>Upload those files into the waivers system</li>
    <li>Complete all these steps 2-3 days before the opening of the quarter to make sure that everything is done
    well in advance!</li>
    </ol>

<h3>How to: add an administrator into the waivers system</h3>
    <p>If you need to add an administrator for the fee waivers system, do the following:
        <ul>
            <li>Go to the "Data administration" site using the links at the top of this page.</li>
            <li>Click on "Users" under the "Auth" section.</li>
            <li>Search for the SUNetID of the person that you want to make an administrator</li>
            <li>Click on their username to open up their user details.</li>
            <li>Under the "permissions" section, check "Staff status" and "Superuser status."</li>
            <li>Save the user.</li>
            <li>The user should now be able to log into the fee waivers system just as you can. There
            is no delay.</li>
        </ul>
    </p>

<h3>How to: add a new quarter</h3>
    <ul>
    <li>Go to the "data administration" site using the links at the top of this page.</li>
    <li>Under the "assu_waivers" section, click on "Terms."</li>
    <li>In the upper-right, select "Add term."</li>
    <li>Follow the instructions and examples to input the correct data.</li>
    <li>Note that the waivers system will open automatically for users at the time specified, and will close
    automatically at the time specified. No further action is necessary to open or close the waivers system.</li>
    </ul>

<h3>How to: Add fees into the quarter</h3>
<ul>
<li>Go to the "data administration" site using the links at the top of this page.</li>
<li>Under the "assu_waivers" section, click on Fees</li>
<li>In the upper-right, select "Add fee."</li>
<li>Fill in the correct information for the fee. Make sure you select the correct quarter.</li>
<li>Click "Save," or click "Save and add another" to make things faster.</li>
</ul>

<h3>How to: Upload the student enrollment information into the system</h3>
<p>The student enrollment information is critical to the system because it determines which students can receive
waivers, and which population they are (since we charge different fees to grads and undergrads.) To avoid having to
manually enter students, we've developed an automatic uploader that uses a format agreed upon between us and SSC.</p>

<p>Before you upload the data, there is NO NEED to edit the content of the SSC files. Never delete students; never
add students; don't adjust their information or anything silly like that. The system is setup to handle the special cases
through the online tool, and you will actually break the online tool somewhat if you edit the content of the files. You
may need to edit the structure or formatting of the file, however, to make sure it matches the specifications below.</p>
    <ul>
    <li>Go to the "Waiver reports" site using the links at the top of this page.</li>
    <li>Find the current quarter, then on the right side, click on "Upload student enrollment information."</li>
    <li>READ THE TEXT AT THE BOTTOM OF THE PAGE OR EVERYTHING CAN BREAK!</li>
    <li>Specifically, ensure that the files are formatted EXACTLY as specified in that text. If you mess up the formatting,
    it's possible that we'll have a ton of really weird data in the database that's impossible to get rid of. But if you
    do mess up, check out the "how to: delete a quarter" below.</li>
    <li>Format the SSC files exactly as specified in that text. This has taken three bullets. It's really important. As
    it says in the text, export the files from Microsoft Excel as "Windows Comma Separated" (on Mac.)</li>
    <li>Select the files in the tool, and click "Upload student enrollment data." The system will chug for a while - don't
    interrupt it! You will see a success message when it is done.</li>
    <li>Under the hood, the system (1) ensures that a "Student" record exists with the specified SUID number, (2) adds
    an "Enrollment" record for the specified student in the current quarter, and then (3) checks if the student needs
    to have a "no waivers" flag set because their SUID number is in the "athletes" file.</li>
    </ul>

<h3>How to: delete a quarter if something went terribly wrong</h3>
    <p>The only time something would go terribly wrong that I can think of is if you somehow uploaded the wrong student
    list into the quarter. However, if anything goes terribly wrong and you just want to start over...</p>
    <ul>
        <li>Go to the "data administration" site using the links at the top of this page.</li>
        <li>Under the "assu_waivers" section, click on "Terms."</li>
        <li>Click on the current quarter, the one that is messed up.</li>
        <li>In the bottom-left, click on "Delete."</li>
        <li>The system will ask if you really want to delete the term, and all its associated records. If you really do,
        click on "Yes, I'm sure."</li>
    </ul>

<h3>How to: access interesting reports</h3>
    <ul>
        <li>Go to the "waiver reports" site using the links at the top of this page</li>
        <li>Select the quarter you want to view reports for, and enjoy.</li>
    </ul>
    <p>The "per-group and aggregate report" is the main report that the ASSU Financial Manager might want to see. It
    lists the amounts that were waived, and gives links to group-specific reports (both internal reports for the FM,
    and the reports that can be printed and given to group officers.)</p>
    <p>Note that the "Group JBL" report is not actually public, and group officers are not actually able to view
    that page. To give that report to a group, you will have to print the page to a PDF and send the group the PDF.</p>
    <p>The "per-student" report is provided in case a student has inquiries about their waivers. There is no search
    function, but I recommend using Command+F in your browser to find a SUNetID or SUID # if you need.</p>

<h3>How to: do more powerful administration</h3>
    <p>The "data administration" site has full control over all the data inside the waivers system, and can be used
    to administrate literally everything. If unusual situations come up and require you to work in-depth, you can use
    that site to look at all the data, delete records, or add records as needed.</p>
    <p>Adding/deleting a fee waiver: this can be accomplished by adding/deleting a "Fee Waiver" object. You can search
    by SUNetID or fee name for existing waivers, filter by quarter, and add records if you need.</p>
    <p>Adding/deleting a student, or changing their "no waivers allowed" flag: there are two sets of records about
    students: their Student record, and their Enrollment records. The Student record contains information linking their
    SUNetID to their SUID # (SUNetID is required to login, and SUID # is required by SSC), the flag that says whether
    or not they are allowed seek waivers, and other information that will stay constant about a student. The Enrollment
    records are short records that just say "Student X is enrolled as a Y (grad/undergrad) in Quarter Z."</p>
    <p>For instance, if SSC requests to see the waivers system as an undergraduate, you will add a Student record with
    a dummy SUID # and the SUNetID of the person who wants to see it, then add an Enrollment record for that student to
    as an undergraduate for the quarter.</p>

<h3>More information; the developer</h3>

    <p>This application was developed by Stephen Trusheim - <a href="mailto:stephen@trushe.im">stephen@trushe.im</a>.
        Its source is available at <a href="http://github.com/trusheim">http://github.com/trusheim</a>. If something
    totally unexpected comes up, let me know.</p>
{% endblock %}

templates/waivers/admin/group_termlistreport.html
{% extends 'waivers/admin/report_base.html' %}
{% load currency %}

{% block title %}
Group waiver report: {{ term }}
{% endblock %}
{% block reportname %}
<a href="{% url 'assu_waivers.admin_views.bygroupTermReport' termName=term.short_name %}">Group waiver reports for {{ term }}</a> &rsaquo;
    Individual group waiver report
{% endblock %}

{% block content %}
    <h2>Waiver report for {{ fee.name }}, {{ term }}</h2>
    <p style='font-style:italic;'>Current as of: {{ date }} </p>

    <p><span style="font-weight:bold;">Fee amount:</span> {{ fee.max_amount|currency }}</p>
    <p><span style="font-weight:bold;">Total amount waived:</span> {{ total_waiver|currency }}</p>
<table>
<thead>
<tr>
    <th>Name</th>
    <th>SUNetID</th>
    <th>SUID #</th>
    <th>Amount</th>
    <th width="20%">Last Updated</th>
    <th>Reason(s)</th>
</tr>
</thead>
<tbody>
{% for waiver in waivers %}
<tr class="{% cycle 'row1' 'row2' %}">
    <th>{{ waiver.student.name }}</th>
    <td>{{ waiver.student.sunetid }}</td>
    <td>{{ waiver.student.suid }}</td>
    <td>{{ waiver.amount|currency }}</td>
    <td>{{ waiver.updated }}</td>
    <td>{{ waiver.reason }}</td>
    <td></td>
</tr>
{% endfor %}
</tbody>

</table>
{% endblock %}

templates/waivers/admin/group_termlistreport_public.html
{% extends 'base.html' %}
{% load currency %}

{% block title %}
Group waiver report: {{ fee.name }}
{% endblock %}

{% block content %}
    <h1>ASSU Student Activity Fee Waiver Report</h1>
        <h2>{{ fee.name }}, {{ term }}</h2>
    <div class='color-box'>
    <p><span style='font-weight:bold;'>To the group President, Financial Officer, and other key officers:</span>
        this document is prepared, pursuant to the
    ASSU Joint Bylaws, to inform you of the students who have received a fee waiver from your group. You are to use
    this document only to ensure that students who have received a waiver do not participate in your group's services.
    </p>
    <p>This document is private, and you may not share it outside the officers listed on your application in OrgSync.
    Spreading this document beyond these authorized users may be considered a violation of the Fundamental Standard
    or Governing Documents of the ASSU, and the student(s) whose privacy rights are infringed may have standing to file
    a case against you and/or your group in the Organizational Conduct Board, Office of Community Standards,
    and/or ASSU Constitutional Council.</p>
    </div>

    <p><span style="font-weight:bold;">Total amount waived:</span> {{ total_waiver|currency }}</p>
<table class='gold-header'>
<thead>
<tr>
    <th>Name</th>
    <th>SUNetID</th>
    <th>SUID #</th>
    <th>Reason(s)</th>
</tr>
</thead>
<tbody>
{% for waiver in waivers %}
<tr class="{% cycle '' 'alternate' %}">
    <td>{{ waiver.student.name }}</td>
    <td>{{ waiver.student.sunetid }}</td>
    <td>{{ waiver.student.suid }}</td>
    <td>{{ waiver.reason }}</td>
</tr>
{% endfor %}
</tbody>

</table>
    <p style='font-style:italic;'>Current as of: {{ date }} </p>

{% endblock %}

templates/waivers/admin/group_termreport.html
{% extends 'waivers/admin/report_base.html' %}
{% load currency %}

{% block title %}
Groups waiver report: {{ term }}
{% endblock %}
{% block reportname %}
Group waiver reports
{% endblock %}

{% block content %}
    <h2>Groups waiver report for {{ term }}</h2>
    <p style='font-style:italic;'>Current as of: {{ date }}</p>
    <h3>Totals</h3>
    <table>
    <thead>
    <tr><td>Population</td><td>Total Waived</td><td>Number of Waivers</td><td>(% of population)</td>
        <td>Enrollment</td><td>Possible Waiver</td></tr>
    </thead>
    <tr><td style="font-weight:bold;">Undergraduate</td><td>{{ stats.total_ug|currency }}</td><td>{{ stats.num_waivers_ug }}</td>
        <td>{{ stats.pct_waivers_ug|floatformat:2 }}%</td><td>{{ stats.enrollment_ug }}</td>
        <td>{{ stats.fee_ug | currency }}</td></tr>
    <tr><td style="font-weight:bold;">Graduate</td><td>{{ stats.total_grad|currency }}</td><td>{{ stats.num_waivers_grad }}</td>
        <td>{{ stats.pct_waivers_grad|floatformat:2 }}%</td><td>{{ stats.enrollment_grad }}</td>
        <td>{{ stats.fee_grad | currency }}</td></tr>
    </table>

    <h3>Fee Summaries</h3>
<table>
<thead>
<tr>
    <th>Name</th>
    <th>Population</th>
    <th>Waivers</th>
    <th>(% of pop)</th>
    <th>Total waived</th>
    <th>Avg waiver (%)</th>
    <th>Fee amount</th>
    <th>Reports</th>


</tr>
</thead>
<tbody>
{% for fee in groups %}
<tr class="{% cycle 'row1' 'row2' %}">
    <th>{{ fee.fee.name|truncatechars:60}}</th>
    <td>{{ fee.fee.get_population_display }}</td>
    <td>{{ fee.count }}</td>
    <td>{{ fee.pct|floatformat:2 }}%</td>
    <td>{{ fee.total|currency }}</td>
    <td>{{ fee.average|currency }} ({{ fee.avg_pct|floatformat:0 }}%)</td>
    <td>{{ fee.fee.max_amount|currency }}</td>
    <td><a href="{% url 'groupreport_private' groupId=fee.fee.pk termName=term.short_name %}">Private</a> /
        <a href="{% url 'groupreport_public' groupId=fee.fee.pk termName=term.short_name %}">Group JBL</a> /
        <a href="{% url 'groupreport_excel' groupId=fee.fee.pk termName=term.short_name %}">JBL Excel</a>
</td>

</tr>
{% endfor %}
</tbody>

</table>
{% endblock %}

templates/waivers/admin/makewaiver.html
{% extends 'waivers/admin/report_base.html' %}

{% block title %}
Administrative waivers
{% endblock %}
{% block reportname %}
    Waiver creation: {{ term }}
{% endblock %}

{% block content %}
    <h2>Administrative waivers: {{ term }}</h2>
    <p>Enter SUNetIDs (the letters, not the numbers) or email addresses @stanford.edu (assumed to be SUNetIDs)
        separated by commas or newlines. Administrative waivers will be created that waive 100% of the possible
    fee for the student.</p>
    <hr />

    <form method = 'POST' action='{% url 'assu_waivers.admin_views.makeFullWaiver' termName=term.short_name %}' accept-charset="UTF-8">
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <span style='font-weight:bold;'>It is a huge pain to undo these, one-by-one. Please be sure you're sure!</span><br />
        <input type='submit' value='Make administrative waivers' />
    </p>
    </form>
{% endblock %}

templates/waivers/admin/report_base.html
{% extends 'admin/base_site.html' %}
{% block title %}
ASSU Waivers Reporting
{% endblock %}

{% block breadcrumbs %}
<div class = 'breadcrumbs'><a href="{% url 'assu_waivers.admin_views.reportIndex' %}">Reports</a> &rsaquo; {% block reportname %}{% endblock %}</div>
{% endblock %}

templates/waivers/admin/report_index.html
{% extends 'waivers/admin/report_base.html' %}
{% load currency %}

{% block title %}
Waiver reports
{% endblock %}
{% block reportname %}
    All
{% endblock %}

{% block content %}
    <h2>Waiver reports</h2>

    <table>
    <thead><tr>
        <td style="border-right:1px solid #ddd">Term</td>
        <td colspan=2 style="border-right:1px solid #ddd">Reports</td>
        <td colspan=2 style="border-right:1px solid #ddd">Export</td>
        <td style="border-right:1px solid #ddd">Administrative</td>

        <td>Import</td>
    </tr></thead>
    {% for term in terms %}
    <tr>
        <td style='font-weight:bold;border-right:1px solid #ddd'>{{ term }}</td>
        <td style="border-right:1px solid #ddd"><a href="{% url 'assu_waivers.admin_views.bygroupTermReport' termName=term.short_name %}">Per-group and aggregate report</a></td>
        <td style="border-right:1px solid #ddd"><a href="{% url 'assu_waivers.admin_views.bystudentTermReport' termName=term.short_name %}">Per-student report</a></td>
        <td style="border-right:1px solid #ddd"><a href="{% url 'assu_waivers.admin_views.exportTermExcel' termName=term.short_name %}">Excel</a></td>
        <td style="border-right:1px solid #ddd"><a href="{% url 'assu_waivers.admin_views.exportTermCsv' termName=term.short_name %}">CSV</a></td>
        <td style="border-right:1px solid #ddd"><a href="{% url 'assu_waivers.admin_views.makeFullWaiver' termName=term.short_name %}">Make Waiver</a></td>
        <td><a href="{% url 'assu_waivers.admin_views.importStudentCsv' termName=term.short_name %}">Upload student enrollment information</a></td>
    </tr>
    {% endfor %}
    </table>
    <br />
    <p>Misc: <a href="/reports/term_info">Term Numbering Info</a></p>
{% endblock %}

templates/waivers/admin/term_info.html
{% extends 'waivers/admin/report_base.html' %}

{% block title %}
    Term name information
{% endblock %}
{% block reportname %}
    Term name information
{% endblock %}

{% block content %}
<h2>Term Naming Information</h2>
<p>Stanford uses numeric codes to refer to each term. These numeric codes are the "short names" of each
term for the waivers system. In short:</p>
<p>4-digit code:
    <ul>
    <li>First digit is a 1</li>
    <li>Second two digits are the two-digit year when the school year ends (e.g.: the 2009-10 school year
        ends in 2010, so the two digits are "10"; the 2012-13 year ends in 2013, so "13")</li>
    <li>The fourth digit is 2 for fall, 4 for winter, 6 for spring, and 8 for summer.</li>
    </ul>
</p>
<h3>Table of Term Numbers</h3>
<p>Here's the codes for upcoming years:</p>
<pre>
1092 -> 2008-09 Autumn
1094 -> 2008-09 Winter
1096 -> 2008-09 Spring
1098 -> 2008-09 Summer
1102 -> 2009-10 Autumn
1104 -> 2009-10 Winter
1106 -> 2009-10 Spring
1108 -> 2009-10 Summer
1112 -> 2010-11 Autumn
1114 -> 2010-11 Winter
1116 -> 2010-11 Spring
1118 -> 2010-11 Summer
1122 -> 2011-12 Autumn
1124 -> 2011-12 Winter
1126 -> 2011-12 Spring
1128 -> 2011-12 Summer
1132 -> 2012-13 Autumn
1134 -> 2012-13 Winter
1136 -> 2012-13 Spring
1138 -> 2012-13 Summer
1142 -> 2013-14 Autumn
1144 -> 2013-14 Winter
1146 -> 2013-14 Spring
1148 -> 2013-14 Summer
1152 -> 2014-15 Autumn
1154 -> 2014-15 Winter
1156 -> 2014-15 Spring
1158 -> 2014-15 Summer
1162 -> 2015-16 Autumn
1164 -> 2015-16 Winter
1166 -> 2015-16 Spring
1168 -> 2015-16 Summer
1172 -> 2016-17 Autumn
1182 -> 2017-18 Autumn
1192 -> 2018-19 Autumn
1202 -> 2019-20 Autumn
</pre>

{% endblock %}

templates/waivers/admin/upload.html
{% extends 'waivers/admin/report_base.html' %}

{% block title %}
Student enrollment upload
{% endblock %}
{% block reportname %}
    Student enrollment upload: {{ term }}
{% endblock %}

{% block content %}
    <h2>Student Enrollment Upload: {{ term }}</h2>
    <p>Please see below for important formatting information.</p>
    <hr />

    <form method = 'POST' action='{% url 'assu_waivers.admin_views.importStudentCsv' termName=term.short_name %}' enctype="multipart/form-data" accept-charset="UTF-8">
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <span style='font-weight:bold;'>THIS ACTION CANNOT BE UNDONE. Please be sure you are uploading the correct files!</span><br />
        <input type='submit' value='Upload student enrollment data' />
    </p>
    </form>
    
    <hr />
    <h3>Formatting information for uploaded files</h3>
    <p><span style='font-weight:bold;'>For both files</span>:
    <ul>
        <li>ALWAYS export files from Microsoft Excel in "Windows Comma Separated" format.</li>
        <li>If you don't do this, you'll get an error like "incorrect string value \x013 for 'name'". This error means you did not export as "Windows Comma Separated".</li>
        <li>File formats must match exactly the specifications below. No header rows. No extraneous columns.</li>
    </ul>
    <p><span style='font-weight:bold;'>Student Data CSV</span>:
    <ul>
        <li>No header row (the first row should be student information)</li>
        <li>Column 1: Numeric SUID</li>
        <li>Column 2: Student Name</li>
        <li>Column 3: SUNetID (login name)</li>
        <li>Column 4: Student Bill Category: UG, GR, GSB, MED, LAW are recognized. GR, GSB, MED, and LAW are all
            considered "GR" (graduate fee)</li>
        <li>Student records are stored with unique numeric SUID. If two records exist with the same SUID, the latter's
        information (name, SUNetID, and billing category) will overwrite the former's. That is one reason
        why there may be fewer students/enrollments reported inside the web tool than on the CSV itself.</li>
        <li>Every student may only be assessed one fee (undergrad or grad).</li>
    </ul></p>
    <p><span style='font-weight:bold;'>Student Athlete CSV</span>:
    <ul>
        <li>No header row (the first row should be student information)</li>
        <li>Column 1: Sport name (no specific format; this is actually discarded)</li>
        <li>Column 2: Student Name</li>
        <li>Column 3: Numeric SUID</li>
        <li>The tool will look for a student with the SUNetID reported in the third column, and set the "no waivers" flag.</li>
    </ul></p>
{% endblock %}

templates/waivers/admin/upload_done.html
{% extends 'waivers/admin/report_base.html' %}
{% load currency %}

{% block title %}
Student enrollment upload
{% endblock %}
{% block reportname %}
    Student enrollment upload
{% endblock %}

{% block content %}
    <h2>Student Enrollment Upload</h2>

    {% if error %}
    <p style='font-weight:bold;'>AN ERROR OCCURRED WHEN UPLOADING! The records have not been successfully updated!</p>
    <p>{{ error }}</p>
    {% else %}
    <p>Upload for {{ term }} completed. {{ num }} enrollment records inserted or updated.</p>
    {% endif %}
{% endblock %}

templates/waivers/admin/user_termreport.html
{% extends 'waivers/admin/report_base.html' %}
{% load currency %}

{% block title %}
Students waiver report: {{ term }}
{% endblock %}
{% block reportname %}
Students waiver report
{% endblock %}

{% block content %}
    <h2>All students waiver report for {{ term }}</h2>
    <p style='font-style:italic;'>Current as of: {{ date }} </p>
    <p>Only students seeking at least one waiver are shown. All other students are not seeking waivers.</p>
<table>
<thead>
<tr>
    <th>SUID</th>
    <th>SUNetID</th>
    <th>Name</th>
    <th>Total waiver</th>
    <th></th>
</tr>
</thead>
<tbody>
{% for report in waivers %}
<tr class="{% cycle 'row1' 'row2' %}">
    <th>{{ report.student__pk }}</th>
    <td>{{ report.student__sunetid }}</td>
    <td>{{ report.student__name }}</td>
    <td>{{ report.total_waiver|currency }}</td>
    <td><a href="{% url 'assu_waivers.admin_views.studentReport' termName=term.short_name student=report.student__sunetid %}">See Waivers</a>
</tr>
{% endfor %}
</tbody>

</table>
{% endblock %}

templates/waivers/admin/user_termreportone.html
{% extends 'waivers/admin/report_base.html' %}
{% load currency %}

{% block title %}
Student Waiver Report: {{ student }} for {{ term }}
{% endblock %}
{% block reportname %}
    <a href="{% url 'assu_waivers.admin_views.bystudentTermReport' termName=term.short_name %}">Student waiver report</a> &rsaquo; {{ student }}
{% endblock %}

{% block content %}
    <h2>Student Waiver Report for {{ student }}, {{ term }}</h2>
    <p style='font-style:italic;'>Current as of: {{ date }}</p>

    <h3>Total Waived</h3>
    {{ total|currency }} / {{ possible|currency }} ({{ enrollment }})
    <h3>Waived Fees</h3>
<table>
<thead>
<tr>
    <th>Name</th>
    <th>Waived</th>
    <th>(Possible)</th>
    <th>Reason</th>
</tr>
</thead>
<tbody>
{% for waiver in waivers %}
<tr class="{% cycle 'row1' 'row2' %}">
    <th>{{ waiver.fee.name }}</th>
    <td>{{ waiver.amount|currency }}</td>
    <td>{{ waiver.fee.max_amount|currency }}</td>
    <td>{{ waiver.reason }}</td>
</tr>
{% endfor %}
<tr>
    <th colspan="3">Fees Not Waived</th>
</tr>
{% for fee in not_waived %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <th>{{ fee.name }}</th>
        <td>{{ 0|currency }}</td>
        <td>{{ fee.max_amount|currency }}</td>
    </tr>
{% endfor %}
</tbody>

</table>
{% endblock %}

templates/waivers/admin/waiverdone.html
{% extends 'waivers/admin/report_base.html' %}

{% block title %}
Student enrollment upload
{% endblock %}
{% block reportname %}
    Waiver creation: {{ term }}
{% endblock %}

{% block content %}
    <h2>Administrative waivers: {{ term }}</h2>
    <p>Waivers have been created for all provided students. All students were found in the waivers system,
    and all have been granted waivers of 100% of their fee.</p>
{% endblock %}